# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

language: python
python: "2.7"
env:
  - TOX_ENV=pep8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
